# Generated by Django 5.1.15 on 2026-07-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Md Mahadi Hasan', max_length=120)),
                ('tagline', models.CharField(default='I make ad spend accountable.', help_text='Short one-liner, e.g. "I make ad spend accountable."', max_length=200)),
                ('hero_eyebrow', models.CharField(default='// PERFORMANCE MARKETER · DHAKA', max_length=120)),
                ('hero_headline', models.CharField(default='Ad spend that answers for itself.', max_length=200)),
                ('hero_subtext', models.TextField(default='I run Meta campaigns for Bangladeshi businesses with proper tracking — Pixel, CAPI, GA4 — so every taka is attributed, and every decision is data. Lower CPL. Higher ROAS. No guesswork.')),
                ('email', models.EmailField(default='mahadihasanshawons@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+8801328885839', max_length=40)),
                ('location', models.CharField(default='Jatrabari, Dhaka, Bangladesh', max_length=160)),
                ('facebook_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Digits only, for wa.me link (e.g. 8801328885839)', max_length=40)),
                ('cv_file', models.FileField(blank=True, upload_to='cv/')),
                ('meta_pixel_id', models.CharField(blank=True, max_length=40)),
                ('og_image', models.ImageField(blank=True, upload_to='og/')),
                ('meta_description', models.TextField(blank=True, default='Md Mahadi Hasan — performance marketer & Meta media buyer in Dhaka. Pixel & CAPI, GA4, Advantage+ campaigns. Lower CPL, higher ROAS.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
