# Generated by Django 5.1.15 on 2026-07-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow_bn',
            field=models.CharField(default='// PERFORMANCE MARKETER · DHAKA', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_eyebrow_en',
            field=models.CharField(default='// PERFORMANCE MARKETER · DHAKA', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_headline_bn',
            field=models.CharField(default='Ad spend that answers for itself.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_headline_en',
            field=models.CharField(default='Ad spend that answers for itself.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtext_bn',
            field=models.TextField(default='I run Meta campaigns for Bangladeshi businesses with proper tracking — Pixel, CAPI, GA4 — so every taka is attributed, and every decision is data. Lower CPL. Higher ROAS. No guesswork.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtext_en',
            field=models.TextField(default='I run Meta campaigns for Bangladeshi businesses with proper tracking — Pixel, CAPI, GA4 — so every taka is attributed, and every decision is data. Lower CPL. Higher ROAS. No guesswork.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='location_bn',
            field=models.CharField(default='Jatrabari, Dhaka, Bangladesh', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='location_en',
            field=models.CharField(default='Jatrabari, Dhaka, Bangladesh', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_bn',
            field=models.TextField(blank=True, default='Md Mahadi Hasan — performance marketer & Meta media buyer in Dhaka. Pixel & CAPI, GA4, Advantage+ campaigns. Lower CPL, higher ROAS.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_en',
            field=models.TextField(blank=True, default='Md Mahadi Hasan — performance marketer & Meta media buyer in Dhaka. Pixel & CAPI, GA4, Advantage+ campaigns. Lower CPL, higher ROAS.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_bn',
            field=models.CharField(default='I make ad spend accountable.', help_text='Short one-liner, e.g. "I make ad spend accountable."', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_en',
            field=models.CharField(default='I make ad spend accountable.', help_text='Short one-liner, e.g. "I make ad spend accountable."', max_length=200, null=True),
        ),
    ]
