# Generated by Django 5.1.15 on 2026-07-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_hero_eyebrow_bn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_eyebrow_bn',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_eyebrow_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_headline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_headline_bn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_headline_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtext',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtext_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtext_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='location',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='location_bn',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='location_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short one-liner, e.g. "I make ad spend accountable."', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline_bn',
            field=models.CharField(blank=True, help_text='Short one-liner, e.g. "I make ad spend accountable."', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline_en',
            field=models.CharField(blank=True, help_text='Short one-liner, e.g. "I make ad spend accountable."', max_length=200, null=True),
        ),
    ]
