# Generated by Django 5.1.15 on 2026-07-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('business', models.CharField(blank=True, help_text='What do you sell?', max_length=200)),
                ('monthly_budget', models.CharField(blank=True, choices=[('<10k', 'Under ৳10k'), ('10-50k', '৳10k–50k'), ('50k+', '৳50k+'), ('na', 'Not sure yet')], max_length=12)),
                ('message', models.TextField(blank=True)),
                ('source_path', models.CharField(blank=True, help_text='Which page/section the lead came from.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
