# Generated by Django 5.1.15 on 2026-07-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='monthly_budget',
            field=models.CharField(blank=True, choices=[('<200', 'Under $200'), ('200-1000', '$200–$1,000'), ('1000+', '$1,000+'), ('na', 'Not sure yet')], max_length=12),
        ),
    ]
