# Generated by Django 5.1.15 on 2026-07-05 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client_type', models.CharField(help_text='e.g. "F-commerce (Fashion)" — anonymized is fine.', max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('challenge', models.TextField()),
                ('approach', models.TextField()),
                ('result_text', models.TextField()),
                ('cover_image', models.ImageField(blank=True, upload_to='cases/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Case studies',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=160)),
                ('role', models.CharField(max_length=160)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text="Leave blank for 'Present'.", null=True)),
                ('summary', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Skill categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StatCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('value', models.FloatField()),
                ('prefix', models.CharField(blank=True, max_length=8)),
                ('suffix', models.CharField(blank=True, max_length=12)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role_company', models.CharField(blank=True, max_length=160)),
                ('quote', models.TextField()),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('before_val', models.CharField(max_length=40)),
                ('after_val', models.CharField(max_length=40)),
                ('direction', models.CharField(choices=[('down_good', 'Lower is better'), ('up_good', 'Higher is better')], default='down_good', max_length=12)),
                ('numeric_before', models.FloatField(blank=True, help_text='For count animation start.', null=True)),
                ('numeric_after', models.FloatField(blank=True, help_text='For count animation end.', null=True)),
                ('prefix', models.CharField(blank=True, help_text='e.g. ৳ (before the animated number).', max_length=8)),
                ('suffix', models.CharField(blank=True, help_text='e.g. x or % (after the animated number).', max_length=8)),
                ('order', models.PositiveIntegerField(default=0)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='portfolio.casestudy')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExperiencePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='portfolio.experience')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('proficiency', models.PositiveSmallIntegerField(default=80, help_text='0–100, drives the animated meter.')),
                ('icon', models.CharField(blank=True, help_text='Optional emoji or inline-SVG name.', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillcategory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
