# Generated by Django 5.1.15 on 2026-07-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='approach_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='approach_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='challenge_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='challenge_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='client_type_bn',
            field=models.CharField(help_text='e.g. "F-commerce (Fashion)" — anonymized is fine.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='client_type_en',
            field=models.CharField(help_text='e.g. "F-commerce (Fashion)" — anonymized is fine.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='result_text_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='result_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='title_bn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='casestudymetric',
            name='label_bn',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='casestudymetric',
            name='label_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_bn',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_bn',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='role_en',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='summary_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='summary_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiencepoint',
            name='text_bn',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='experiencepoint',
            name='text_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='name_bn',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='name_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='statcounter',
            name='label_bn',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='statcounter',
            name='label_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role_company_bn',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role_company_en',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
