# Generated by Django 5.1.15 on 2026-07-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_casestudy_approach_bn_casestudy_approach_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudymetric',
            name='prefix',
            field=models.CharField(blank=True, help_text='e.g. $ (before the animated number).', max_length=8),
        ),
    ]
