# Generated by Django 5.1.15 on 2026-07-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_casestudymetric_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategory',
            name='slug',
            field=models.SlugField(default='', max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
