# Generated by Django 5.1.15 on 2026-09-28 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_skillcategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Blur client names, ad account IDs and personal data before uploading.', upload_to='cases/screenshots/')),
                ('kind', models.CharField(choices=[('ads_manager', 'Ads Manager'), ('events', 'Events Manager / Pixel'), ('analytics', 'Analytics'), ('creative', 'Ad creative'), ('sales', 'Sales / Orders'), ('other', 'Other')], default='ads_manager', max_length=20)),
                ('caption', models.CharField(blank=True, help_text='e.g. "Campaign results — last 30 days".', max_length=200)),
                ('caption_en', models.CharField(blank=True, help_text='e.g. "Campaign results — last 30 days".', max_length=200, null=True)),
                ('caption_bn', models.CharField(blank=True, help_text='e.g. "Campaign results — last 30 days".', max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='portfolio.casestudy')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
